import isBase64 from "@/utils/isBase64";
import getBase64Url from "@/utils/getBase64Url";

import { normalizeUrl } from "../normalizeUrl";

jest.mock("@/utils/isBase64");
jest.mock("@/utils/getBase64Url");

const mockedIsBase64 = jest.mocked(isBase64);
const mockedGetBase64Url = jest.mocked(getBase64Url);

describe("normalizeUrl", () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it("returns an empty string when files are not provided", async () => {
    await expect(normalizeUrl()).resolves.toBe("");
  });

  it("returns an empty string when files array is empty", async () => {
    await expect(normalizeUrl([])).resolves.toBe("");
  });

  it("returns the file when it is already base64", async () => {
    const base64 = "data:image/png;base64,iVBORw0KGgo=";

    mockedIsBase64.mockReturnValue(true);

    await expect(normalizeUrl([base64])).resolves.toBe(base64);

    expect(mockedIsBase64).toHaveBeenCalledWith(base64);
    expect(mockedGetBase64Url).not.toHaveBeenCalled();
  });

  it("returns base64 generated by getBase64 when file is not base64", async () => {
    const file = new File(["test"], "test.png", {
      type: "image/png",
    });
    const base64 = "data:image/png;base64,generated";

    mockedIsBase64.mockReturnValue(false);
    mockedGetBase64Url.mockResolvedValue(base64);

    await expect(normalizeUrl([file])).resolves.toBe(base64);

    expect(mockedIsBase64).toHaveBeenCalledWith(file);
    expect(mockedGetBase64Url).toHaveBeenCalledWith(file);
  });
});
